// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Models;

namespace Pokedex.Migrations
{
    [DbContext(typeof(DBPokedexContext))]
    [Migration("20200315184428_AlterRowNameTablePokemon")]
    partial class AlterRowNameTablePokemon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokedex.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Powers")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("RegionFk")
                        .IsRequired()
                        .HasColumnName("Region_Fk");

                    b.Property<int?>("TypeFk")
                        .IsRequired()
                        .HasColumnName("Type_Fk");

                    b.HasKey("Id");

                    b.HasIndex("RegionFk");

                    b.HasIndex("TypeFk");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("Pokedex.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Pokedex.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Pokedex.Models.Pokemon", b =>
                {
                    b.HasOne("Pokedex.Models.Region", "RegionFkNavigation")
                        .WithMany("Pokemon")
                        .HasForeignKey("RegionFk")
                        .HasConstraintName("FK_Pokemon_Region")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokedex.Models.Type", "TypeFkNavigation")
                        .WithMany("Pokemon")
                        .HasForeignKey("TypeFk")
                        .HasConstraintName("FK_Pokemon_Type")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
